### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by hmoldenhauer** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#1]
- [x] Domain sichern
- [x] Design überarbeiten
- [x] Content eintragen
- [x] Thilo hinzufügen
- [x] Readme überarbeiten
- [x] Eine Contributing erstellen, sodass eigenständig Posts erstellt werden können
- [x] Fotos für die Zeltlager von Clint bekommen (jeweils 1 sollte reichen?!)

**Comment by hmoldenhauer** [comment]
Das Design haben wir eigentlich überarbeitet, oder?

**Comment by tuerex** [comment]
Jo, ich bin damit sehr einverstanden.

**Comment by hmoldenhauer** [comment]
Habe die Domain bei Clint angefragt. Bekommen wir die Tage zugeschickt.

**Comment by hmoldenhauer** [comment]
Die Zeltlagerfotos auf dem Server sind nicht hoch aufgelößt. Wir können sie aber herunter laden. Mache ich die Tage

**Comment by tuerex** [comment]
Ich habe als das "bildhochladen" als contributing verpackt und zusammen mit dem Readme ist das eine gute Anleitung/Erinnerungsstütze für alle, die auf der Website posten wollen.

**Comment by hmoldenhauer** [comment]
Alles abgehakt
