### ISSUE TITLE
Merging of Master & Redesign

### ISSUE THREAD

**Issue by tuerex** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#10]
Ich finde es ist an der Zeit die Branches zu mergen, damit wir der Pfarrleitung unseren Status quo überall zeigen und vielleicht schon mal die ersten Reaktionen bekommen können.

**Comment by hmoldenhauer** [comment]
Ich schaue gleich noch einmal kurz drüber.
Kannst du schon mal eine Mail aufsetzen? Dann können wir das heute evtl. noch fertig machen.

**Comment by hmoldenhauer** [comment]
Habe noch ein paar Änderungen vorgenommen: Der Titel wird jetzt statt Lupe angezeigt. Ich habe das css noch etwas eleganter gemacht. Da muss aber noch einiges dran überarbeitet werden.

Du kannst jetzt jedenfalls den Pullrequest reviewen und das ganze dann mergen

**Comment by tuerex** [comment]
Email geschrieben, Pullrequest granded.
