### ISSUE TITLE
Bilder sinnvoll ablegen

### ISSUE THREAD

**Issue by hmoldenhauer** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#13]
Die Bilder liegen bisher alle im Ordner aktuelles. Hier sollte es zumindest noch einen für Zeltlager geben. Evtl. aktuelles löschen. Das muss dann aber in den entsprechenden .html Dateien geändert werden

**Comment by tuerex** [comment]
Für Zeltlager angepasst.
sollte für deutlich mehr Ordnung sorgen.
