### ISSUE TITLE
Änderung der Reihenfolge

### ISSUE THREAD

**Issue by JuliaTopaz** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#39]
Könnte als erster Reiter vor "Aktuelles" der Reiter "Über uns" erscheinen, aber in abgespeckt ohne die Infos über die KJG? Der alte Reiter "Über uns" sollte dann in "KJG" umbenannt werden und die Hintergrund Infos enthalten.

**Comment by hmoldenhauer** [comment]
Habe ich mal im branch umstrukturierung realisiert. Sollte soweit okay sein, bitte einmal anschauen

**Comment by hmoldenhauer** [comment]
Ist gemerged, daher
