### ISSUE TITLE
Fotos Hochladen von Julia (und anderen Usern)

### ISSUE THREAD

**Issue by tuerex** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#46]
es gibt ein Berechtigungsproblem, sodass Julia keine Fotos per Drag & Drop hochladen kann.

**Comment by hmoldenhauer** [comment]
Mmh, ich bin mir nicht sicher, ob das ein Berechtigungsproblem ist. Am besten testen wir das mal mit nem dummy-account

**Comment by hmoldenhauer** [comment]
erledigt
