### ISSUE TITLE
Datensicherung der alten Seite

### ISSUE THREAD

**Issue by JuliaTopaz** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#48]
Habt ihr Clint mal gefragt wie wir das Zeltlager-Archiv an Fotos sichern können?

**Comment by hmoldenhauer** [comment]
Ich habe nen Dropboxlink von ihm. Ich muss die Daten mal runterladen -.-'

**Comment by hmoldenhauer** [comment]
Habe ich bei mir auf dem Rechner
