### ISSUE TITLE
Pfarrleitung

### ISSUE THREAD

**Issue by JuliaTopaz** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#49]
Im Punkt "Über uns" stimmt die Zusammensetzung der Pfarrleitung nicht, Lara und Finn fehlen und Nadine ist mittlerweile raus. Ich weiß nicht wie ich das ändern kann.

**Comment by hmoldenhauer** [comment]
Kümmern wir uns spätestens am 22. drum

**Comment by tuerex** [comment]
ist schon erledigt.
