### ISSUE TITLE
Über Uns

### ISSUE THREAD

**Issue by tuerex** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#5]
Wieviel schreiben wir in den Teil "Über Uns"?
Konzept: Ein bisschen was erzählen über uns und unsere aktuellen Gruppenstunden sowie Pfarrleitung.

**Comment by hmoldenhauer** [comment]
Ist soweit erst mal okay.
Wenn da noch Kommentare seitens der Pfarrleitung sind, machen wir nen neues Issue auf
