### ISSUE TITLE
Aktuelles

### ISSUE THREAD

**Issue by hmoldenhauer** [kjg-dortmund-wickede/kjg-dortmund-wickede.github.io#66]
Es sollten maximal 6 Posts unter 'Aktuelles' stehen.
Wie siehst du das @tuerex ?

**Comment by tuerex** [comment]
ja, finde ich auch.
ist lange genug her.

2018-01-12 14:30 GMT+01:00 hmoldenhauer <notifications@github.com>:

**Comment by tuerex** [comment]
Habe einen Pullreqeust gestellt.
